##Q1.Retrieve the total number of rentals made in the Sakila database. 
SELECT count(rental_id) FROM mavenmovies.rental ;

##Q2.Find the average rental duration (in days) of movies rented from the Sakila database.
SELECT avg(rental_duration) AS Avg_Rental FROM mavenmovies.film ;

## string function
##Q3.Display the first name and last name of customers in uppercase. 
SELECT upper(first_name),(last_name) AS Upper_case FROM mavenmovies.customer ;

##Q4.Extract the month from the rental date and display it alongside the rental ID. 
SELECT rental_id,month(return_date) FROM mavenmovies.rental ;

##group by
##Q5.Retrieve the count of rentals for each customer (display customer ID and the count of rentals). 
SELECT customer_id,count(rental_id) FROM mavenmovies.rental group by customer_id ;

##Q6.Find the total revenue generated by each store. 
select 
  sum(payment.amount) AS total_revenue,
  store.store_id
  from payment 
  join customer
  ON payment.customer_id = customer.customer_id
  Join store
  ON customer.store_id = store.store_id
  group by store.store_id ;

##joins
##.Display the title of the movie, customers first name, and last name who rented it. 
SELECT 
	film.title AS Movie_name,
    film.rental_rate AS Rent,
    customer.first_name AS customer_first_name,
    customer.last_name AS customer_last_name
FROM rental
JOIN customer ON rental.customer_id = customer.customer_id
join inventory ON rental.inventory_id = inventory.inventory_id
Join film on inventory.film_id = film.film_id;

##.Retrieve the names of all actors who have appeared in the film "ACADEMY DINOSAUR." 
select 
   actor.first_name AS Actor_name,
   film.title AS film_name
   from actor 
   join film_actor 
   on actor.actor_id = film_actor.actor_id
   Join film 
   on film_actor.film_id = film.film_id
   where film.title = "ACADEMY DINOSAUR"; 
   
   ##Join & group by
   ##.Determine the total number of rentals for each category of movies.
   SELECT category.name AS category_name, COUNT(rental.rental_id) AS total_rentals
FROM rental
JOIN inventory ON rental.inventory_id = inventory.inventory_id
JOIN film ON inventory.film_id = film.film_id
JOIN film_category ON film.film_id = film_category.film_id
JOIN category ON film_category.category_id = category.category_id
GROUP BY category.name
ORDER BY total_rentals DESC;

##.Find the average rental rate of movies in each language. 
     SELECT language.name AS language_name, AVG(film.rental_rate) AS average_rental_rate
FROM film
JOIN language ON film.language_id = language.language_id
GROUP BY language.name;

##.Retrieve the customer names along with the total amount they've spent on rentals. 
select 
   customer.first_name AS Customer_name,
   sum(payment.amount) AS Total_amount,
   rental.rental_id AS Rental
   from customer 
   Join rental
   On customer.customer_id = rental.customer_id
   Join payment 
   ON customer.customer_id = payment.customer_id
   group by rental.rental_id;

##.List the titles of movies rented by each customer in a particular city (e.g., 'London'). 
select 
    film.title AS Movie_title,
    customer.first_name AS customer_Name,
    rental.rental_id AS Rental,
    city 
    from rental
    Join customer
    ON rental.customer_id = customer.customer_id
    Join inventory
    ON rental.inventory_id = inventory.inventory_id
    Join film
    ON inventory.film_id = film.film_id 
    Join address
    ON customer.address_id = address.address_id
    Join city
    ON address.city_id = city.city_id
    where city = "london"
    group by rental_id;

##.Display the top 5 rented movies along with the number of times they've been rented
select 
film.title AS Title,
count(rental.rental_id) AS Rented
from film
join inventory
ON film.film_id = inventory.film_id
Join rental
ON inventory.inventory_id = rental.inventory_id
group by film.film_id 
order by film.film_id desc limit 5;

##Determine the customers who have rented movies from both stores (store ID 1 and store ID 2). 
select 
 customer.first_name AS customer_name,
 film.title AS Rented_Movies,
count(rental.rental_id) AS Rental,
 store.store_id
 from customer
 join rental
 ON customer.customer_id=rental.customer_id
 join store
 ON customer.store_id = store.store_id
 Join inventory 
 ON rental.inventory_id = inventory.inventory_id
 join film
 ON inventory.film_id = film.film_id
 where store.store_id in ("1","2")
 group by rental.rental_id;
 
 
 




